package models_mappings

type Item struct {
	AbyssalEssence          ItemInfo `json:"/items/abyssal_essence"`
	AcrobaticHood           ItemInfo `json:"/items/acrobatic_hood"`
	AcrobatsRibbon          ItemInfo `json:"/items/acrobats_ribbon"`
	AdvancedTaskBadge       ItemInfo `json:"/items/advanced_task_badge"`
	Amber                   ItemInfo `json:"/items/amber"`
	Amethyst                ItemInfo `json:"/items/amethyst"`
	Apple                   ItemInfo `json:"/items/apple"`
	AppleGummy              ItemInfo `json:"/items/apple_gummy"`
	AppleYogurt             ItemInfo `json:"/items/apple_yogurt"`
	AquaArrow               ItemInfo `json:"/items/aqua_arrow"`
	AquaAura                ItemInfo `json:"/items/aqua_aura"`
	AquaEssence             ItemInfo `json:"/items/aqua_essence"`
	ArabicaCoffeeBean       ItemInfo `json:"/items/arabica_coffee_bean"`
	ArcaneBow               ItemInfo `json:"/items/arcane_bow"`
	ArcaneCrossbow          ItemInfo `json:"/items/arcane_crossbow"`
	ArcaneFireStaff         ItemInfo `json:"/items/arcane_fire_staff"`
	ArcaneLog               ItemInfo `json:"/items/arcane_log"`
	ArcaneLumber            ItemInfo `json:"/items/arcane_lumber"`
	ArcaneNatureStaff       ItemInfo `json:"/items/arcane_nature_staff"`
	ArcaneReflection        ItemInfo `json:"/items/arcane_reflection"`
	ArcaneShield            ItemInfo `json:"/items/arcane_shield"`
	ArcaneWaterStaff        ItemInfo `json:"/items/arcane_water_staff"`
	ArtisanTea              ItemInfo `json:"/items/artisan_tea"`
	AttackCoffee            ItemInfo `json:"/items/attack_coffee"`
	AzureBoots              ItemInfo `json:"/items/azure_boots"`
	AzureBrush              ItemInfo `json:"/items/azure_brush"`
	AzureBuckler            ItemInfo `json:"/items/azure_buckler"`
	AzureBulwark            ItemInfo `json:"/items/azure_bulwark"`
	AzureCheese             ItemInfo `json:"/items/azure_cheese"`
	AzureChisel             ItemInfo `json:"/items/azure_chisel"`
	AzureEnhancer           ItemInfo `json:"/items/azure_enhancer"`
	AzureGauntlets          ItemInfo `json:"/items/azure_gauntlets"`
	AzureHammer             ItemInfo `json:"/items/azure_hammer"`
	AzureHatchet            ItemInfo `json:"/items/azure_hatchet"`
	AzureHelmet             ItemInfo `json:"/items/azure_helmet"`
	AzureMace               ItemInfo `json:"/items/azure_mace"`
	AzureMilk               ItemInfo `json:"/items/azure_milk"`
	AzureNeedle             ItemInfo `json:"/items/azure_needle"`
	AzurePlateBody          ItemInfo `json:"/items/azure_plate_body"`
	AzurePlateLegs          ItemInfo `json:"/items/azure_plate_legs"`
	AzurePot                ItemInfo `json:"/items/azure_pot"`
	AzureShears             ItemInfo `json:"/items/azure_shears"`
	AzureSpatula            ItemInfo `json:"/items/azure_spatula"`
	AzureSpear              ItemInfo `json:"/items/azure_spear"`
	AzureSword              ItemInfo `json:"/items/azure_sword"`
	BagOf10Cowbells         ItemInfo `json:"/items/bag_of_10_cowbells"`
	BambooBoots             ItemInfo `json:"/items/bamboo_boots"`
	BambooBranch            ItemInfo `json:"/items/bamboo_branch"`
	BambooFabric            ItemInfo `json:"/items/bamboo_fabric"`
	BambooGloves            ItemInfo `json:"/items/bamboo_gloves"`
	BambooHat               ItemInfo `json:"/items/bamboo_hat"`
	BambooRobeBottoms       ItemInfo `json:"/items/bamboo_robe_bottoms"`
	BambooRobeTop           ItemInfo `json:"/items/bamboo_robe_top"`
	BasicTaskBadge          ItemInfo `json:"/items/basic_task_badge"`
	BearEssence             ItemInfo `json:"/items/bear_essence"`
	BeastBoots              ItemInfo `json:"/items/beast_boots"`
	BeastBracers            ItemInfo `json:"/items/beast_bracers"`
	BeastChaps              ItemInfo `json:"/items/beast_chaps"`
	BeastHide               ItemInfo `json:"/items/beast_hide"`
	BeastHood               ItemInfo `json:"/items/beast_hood"`
	BeastLeather            ItemInfo `json:"/items/beast_leather"`
	BeastTunic              ItemInfo `json:"/items/beast_tunic"`
	Berserk                 ItemInfo `json:"/items/berserk"`
	BirchBow                ItemInfo `json:"/items/birch_bow"`
	BirchCrossbow           ItemInfo `json:"/items/birch_crossbow"`
	BirchFireStaff          ItemInfo `json:"/items/birch_fire_staff"`
	BirchLog                ItemInfo `json:"/items/birch_log"`
	BirchLumber             ItemInfo `json:"/items/birch_lumber"`
	BirchNatureStaff        ItemInfo `json:"/items/birch_nature_staff"`
	BirchShield             ItemInfo `json:"/items/birch_shield"`
	BirchWaterStaff         ItemInfo `json:"/items/birch_water_staff"`
	BishopsCodex            ItemInfo `json:"/items/bishops_codex"`
	BishopsScroll           ItemInfo `json:"/items/bishops_scroll"`
	BlackBearFluff          ItemInfo `json:"/items/black_bear_fluff"`
	BlackBearShoes          ItemInfo `json:"/items/black_bear_shoes"`
	BlackTeaLeaf            ItemInfo `json:"/items/black_tea_leaf"`
	Blackberry              ItemInfo `json:"/items/blackberry"`
	BlackberryCake          ItemInfo `json:"/items/blackberry_cake"`
	BlackberryDonut         ItemInfo `json:"/items/blackberry_donut"`
	BlessedTea              ItemInfo `json:"/items/blessed_tea"`
	BlueKeyFragment         ItemInfo `json:"/items/blue_key_fragment"`
	Blueberry               ItemInfo `json:"/items/blueberry"`
	BlueberryCake           ItemInfo `json:"/items/blueberry_cake"`
	BlueberryDonut          ItemInfo `json:"/items/blueberry_donut"`
	BrewingTea              ItemInfo `json:"/items/brewing_tea"`
	BrownKeyFragment        ItemInfo `json:"/items/brown_key_fragment"`
	BurbleBoots             ItemInfo `json:"/items/burble_boots"`
	BurbleBrush             ItemInfo `json:"/items/burble_brush"`
	BurbleBuckler           ItemInfo `json:"/items/burble_buckler"`
	BurbleBulwark           ItemInfo `json:"/items/burble_bulwark"`
	BurbleCheese            ItemInfo `json:"/items/burble_cheese"`
	BurbleChisel            ItemInfo `json:"/items/burble_chisel"`
	BurbleEnhancer          ItemInfo `json:"/items/burble_enhancer"`
	BurbleGauntlets         ItemInfo `json:"/items/burble_gauntlets"`
	BurbleHammer            ItemInfo `json:"/items/burble_hammer"`
	BurbleHatchet           ItemInfo `json:"/items/burble_hatchet"`
	BurbleHelmet            ItemInfo `json:"/items/burble_helmet"`
	BurbleMace              ItemInfo `json:"/items/burble_mace"`
	BurbleMilk              ItemInfo `json:"/items/burble_milk"`
	BurbleNeedle            ItemInfo `json:"/items/burble_needle"`
	BurblePlateBody         ItemInfo `json:"/items/burble_plate_body"`
	BurblePlateLegs         ItemInfo `json:"/items/burble_plate_legs"`
	BurblePot               ItemInfo `json:"/items/burble_pot"`
	BurbleShears            ItemInfo `json:"/items/burble_shears"`
	BurbleSpatula           ItemInfo `json:"/items/burble_spatula"`
	BurbleSpear             ItemInfo `json:"/items/burble_spear"`
	BurbleSword             ItemInfo `json:"/items/burble_sword"`
	BurbleTeaLeaf           ItemInfo `json:"/items/burble_tea_leaf"`
	BurningKeyFragment      ItemInfo `json:"/items/burning_key_fragment"`
	CedarBow                ItemInfo `json:"/items/cedar_bow"`
	CedarCrossbow           ItemInfo `json:"/items/cedar_crossbow"`
	CedarFireStaff          ItemInfo `json:"/items/cedar_fire_staff"`
	CedarLog                ItemInfo `json:"/items/cedar_log"`
	CedarLumber             ItemInfo `json:"/items/cedar_lumber"`
	CedarNatureStaff        ItemInfo `json:"/items/cedar_nature_staff"`
	CedarShield             ItemInfo `json:"/items/cedar_shield"`
	CedarWaterStaff         ItemInfo `json:"/items/cedar_water_staff"`
	CentaurBoots            ItemInfo `json:"/items/centaur_boots"`
	CentaurHoof             ItemInfo `json:"/items/centaur_hoof"`
	ChannelingCoffee        ItemInfo `json:"/items/channeling_coffee"`
	ChaoticChain            ItemInfo `json:"/items/chaotic_chain"`
	ChaoticFlail            ItemInfo `json:"/items/chaotic_flail"`
	Cheese                  ItemInfo `json:"/items/cheese"`
	CheeseBoots             ItemInfo `json:"/items/cheese_boots"`
	CheeseBrush             ItemInfo `json:"/items/cheese_brush"`
	CheeseBuckler           ItemInfo `json:"/items/cheese_buckler"`
	CheeseBulwark           ItemInfo `json:"/items/cheese_bulwark"`
	CheeseChisel            ItemInfo `json:"/items/cheese_chisel"`
	CheeseEnhancer          ItemInfo `json:"/items/cheese_enhancer"`
	CheeseGauntlets         ItemInfo `json:"/items/cheese_gauntlets"`
	CheeseHammer            ItemInfo `json:"/items/cheese_hammer"`
	CheeseHatchet           ItemInfo `json:"/items/cheese_hatchet"`
	CheeseHelmet            ItemInfo `json:"/items/cheese_helmet"`
	CheeseMace              ItemInfo `json:"/items/cheese_mace"`
	CheeseNeedle            ItemInfo `json:"/items/cheese_needle"`
	CheesePlateBody         ItemInfo `json:"/items/cheese_plate_body"`
	CheesePlateLegs         ItemInfo `json:"/items/cheese_plate_legs"`
	CheesePot               ItemInfo `json:"/items/cheese_pot"`
	CheeseShears            ItemInfo `json:"/items/cheese_shears"`
	CheeseSpatula           ItemInfo `json:"/items/cheese_spatula"`
	CheeseSpear             ItemInfo `json:"/items/cheese_spear"`
	CheeseSword             ItemInfo `json:"/items/cheese_sword"`
	CheesesmithingTea       ItemInfo `json:"/items/cheesesmithing_tea"`
	ChimericalChest         ItemInfo `json:"/items/chimerical_chest"`
	ChimericalChestKey      ItemInfo `json:"/items/chimerical_chest_key"`
	ChimericalEntryKey      ItemInfo `json:"/items/chimerical_entry_key"`
	ChimericalEssence       ItemInfo `json:"/items/chimerical_essence"`
	ChimericalQuiver        ItemInfo `json:"/items/chimerical_quiver"`
	ChimericalToken         ItemInfo `json:"/items/chimerical_token"`
	ChronoGloves            ItemInfo `json:"/items/chrono_gloves"`
	ChronoSphere            ItemInfo `json:"/items/chrono_sphere"`
	Cleave                  ItemInfo `json:"/items/cleave"`
	Cocoon                  ItemInfo `json:"/items/cocoon"`
	Coin                    ItemInfo `json:"/items/coin"`
	CollectorsBoots         ItemInfo `json:"/items/collectors_boots"`
	ColossusCore            ItemInfo `json:"/items/colossus_core"`
	ColossusPlateBody       ItemInfo `json:"/items/colossus_plate_body"`
	ColossusPlateLegs       ItemInfo `json:"/items/colossus_plate_legs"`
	CookingTea              ItemInfo `json:"/items/cooking_tea"`
	Cotton                  ItemInfo `json:"/items/cotton"`
	CottonBoots             ItemInfo `json:"/items/cotton_boots"`
	CottonFabric            ItemInfo `json:"/items/cotton_fabric"`
	CottonGloves            ItemInfo `json:"/items/cotton_gloves"`
	CottonHat               ItemInfo `json:"/items/cotton_hat"`
	CottonRobeBottoms       ItemInfo `json:"/items/cotton_robe_bottoms"`
	CottonRobeTop           ItemInfo `json:"/items/cotton_robe_top"`
	Cowbell                 ItemInfo `json:"/items/cowbell"`
	CrabPincer              ItemInfo `json:"/items/crab_pincer"`
	CraftingTea             ItemInfo `json:"/items/crafting_tea"`
	CrimsonBoots            ItemInfo `json:"/items/crimson_boots"`
	CrimsonBrush            ItemInfo `json:"/items/crimson_brush"`
	CrimsonBuckler          ItemInfo `json:"/items/crimson_buckler"`
	CrimsonBulwark          ItemInfo `json:"/items/crimson_bulwark"`
	CrimsonCheese           ItemInfo `json:"/items/crimson_cheese"`
	CrimsonChisel           ItemInfo `json:"/items/crimson_chisel"`
	CrimsonEnhancer         ItemInfo `json:"/items/crimson_enhancer"`
	CrimsonGauntlets        ItemInfo `json:"/items/crimson_gauntlets"`
	CrimsonHammer           ItemInfo `json:"/items/crimson_hammer"`
	CrimsonHatchet          ItemInfo `json:"/items/crimson_hatchet"`
	CrimsonHelmet           ItemInfo `json:"/items/crimson_helmet"`
	CrimsonMace             ItemInfo `json:"/items/crimson_mace"`
	CrimsonMilk             ItemInfo `json:"/items/crimson_milk"`
	CrimsonNeedle           ItemInfo `json:"/items/crimson_needle"`
	CrimsonPlateBody        ItemInfo `json:"/items/crimson_plate_body"`
	CrimsonPlateLegs        ItemInfo `json:"/items/crimson_plate_legs"`
	CrimsonPot              ItemInfo `json:"/items/crimson_pot"`
	CrimsonShears           ItemInfo `json:"/items/crimson_shears"`
	CrimsonSpatula          ItemInfo `json:"/items/crimson_spatula"`
	CrimsonSpear            ItemInfo `json:"/items/crimson_spear"`
	CrimsonSword            ItemInfo `json:"/items/crimson_sword"`
	CripplingSlash          ItemInfo `json:"/items/crippling_slash"`
	CriticalAura            ItemInfo `json:"/items/critical_aura"`
	CriticalCoffee          ItemInfo `json:"/items/critical_coffee"`
	CrushedAmber            ItemInfo `json:"/items/crushed_amber"`
	CrushedAmethyst         ItemInfo `json:"/items/crushed_amethyst"`
	CrushedGarnet           ItemInfo `json:"/items/crushed_garnet"`
	CrushedJade             ItemInfo `json:"/items/crushed_jade"`
	CrushedMoonstone        ItemInfo `json:"/items/crushed_moonstone"`
	CrushedPearl            ItemInfo `json:"/items/crushed_pearl"`
	Cupcake                 ItemInfo `json:"/items/cupcake"`
	CursedBall              ItemInfo `json:"/items/cursed_ball"`
	CursedBow               ItemInfo `json:"/items/cursed_bow"`
	DarkKeyFragment         ItemInfo `json:"/items/dark_key_fragment"`
	DefenseCoffee           ItemInfo `json:"/items/defense_coffee"`
	DemonicCore             ItemInfo `json:"/items/demonic_core"`
	DemonicPlateBody        ItemInfo `json:"/items/demonic_plate_body"`
	DemonicPlateLegs        ItemInfo `json:"/items/demonic_plate_legs"`
	DodocamelGauntlets      ItemInfo `json:"/items/dodocamel_gauntlets"`
	DodocamelPlume          ItemInfo `json:"/items/dodocamel_plume"`
	Donut                   ItemInfo `json:"/items/donut"`
	DragonFruit             ItemInfo `json:"/items/dragon_fruit"`
	DragonFruitGummy        ItemInfo `json:"/items/dragon_fruit_gummy"`
	DragonFruitYogurt       ItemInfo `json:"/items/dragon_fruit_yogurt"`
	EarringsOfArmor         ItemInfo `json:"/items/earrings_of_armor"`
	EarringsOfGathering     ItemInfo `json:"/items/earrings_of_gathering"`
	EarringsOfRareFind      ItemInfo `json:"/items/earrings_of_rare_find"`
	EarringsOfRegeneration  ItemInfo `json:"/items/earrings_of_regeneration"`
	EarringsOfResistance    ItemInfo `json:"/items/earrings_of_resistance"`
	EarringsOfThreat        ItemInfo `json:"/items/earrings_of_threat"`
	EfficiencyTea           ItemInfo `json:"/items/efficiency_tea"`
	Egg                     ItemInfo `json:"/items/egg"`
	ElementalAffinity       ItemInfo `json:"/items/elemental_affinity"`
	Elusiveness             ItemInfo `json:"/items/elusiveness"`
	EmpTeaLeaf              ItemInfo `json:"/items/emp_tea_leaf"`
	EnchantedChest          ItemInfo `json:"/items/enchanted_chest"`
	EnchantedChestKey       ItemInfo `json:"/items/enchanted_chest_key"`
	EnchantedCloak          ItemInfo `json:"/items/enchanted_cloak"`
	EnchantedEntryKey       ItemInfo `json:"/items/enchanted_entry_key"`
	EnchantedEssence        ItemInfo `json:"/items/enchanted_essence"`
	EnchantedGloves         ItemInfo `json:"/items/enchanted_gloves"`
	EnchantedToken          ItemInfo `json:"/items/enchanted_token"`
	EnhancingTea            ItemInfo `json:"/items/enhancing_tea"`
	Entangle                ItemInfo `json:"/items/entangle"`
	ExcelsaCoffeeBean       ItemInfo `json:"/items/excelsa_coffee_bean"`
	ExpertTaskBadge         ItemInfo `json:"/items/expert_task_badge"`
	EyeOfTheWatcher         ItemInfo `json:"/items/eye_of_the_watcher"`
	EyeWatch                ItemInfo `json:"/items/eye_watch"`
	Eyessence               ItemInfo `json:"/items/eyessence"`
	FierceAura              ItemInfo `json:"/items/fierce_aura"`
	FieriosaCoffeeBean      ItemInfo `json:"/items/fieriosa_coffee_bean"`
	FighterNecklace         ItemInfo `json:"/items/fighter_necklace"`
	Fireball                ItemInfo `json:"/items/fireball"`
	Firestorm               ItemInfo `json:"/items/firestorm"`
	FlameArrow              ItemInfo `json:"/items/flame_arrow"`
	FlameAura               ItemInfo `json:"/items/flame_aura"`
	FlameBlast              ItemInfo `json:"/items/flame_blast"`
	FlamingCloth            ItemInfo `json:"/items/flaming_cloth"`
	FlamingRobeBottoms      ItemInfo `json:"/items/flaming_robe_bottoms"`
	FlamingRobeTop          ItemInfo `json:"/items/flaming_robe_top"`
	Flax                    ItemInfo `json:"/items/flax"`
	FluffyRedHat            ItemInfo `json:"/items/fluffy_red_hat"`
	ForagingTea             ItemInfo `json:"/items/foraging_tea"`
	Frenzy                  ItemInfo `json:"/items/frenzy"`
	FrostSphere             ItemInfo `json:"/items/frost_sphere"`
	FrostStaff              ItemInfo `json:"/items/frost_staff"`
	FrostSurge              ItemInfo `json:"/items/frost_surge"`
	Garnet                  ItemInfo `json:"/items/garnet"`
	GatheringTea            ItemInfo `json:"/items/gathering_tea"`
	GatorVest               ItemInfo `json:"/items/gator_vest"`
	GiantPouch              ItemInfo `json:"/items/giant_pouch"`
	GinkgoBow               ItemInfo `json:"/items/ginkgo_bow"`
	GinkgoCrossbow          ItemInfo `json:"/items/ginkgo_crossbow"`
	GinkgoFireStaff         ItemInfo `json:"/items/ginkgo_fire_staff"`
	GinkgoLog               ItemInfo `json:"/items/ginkgo_log"`
	GinkgoLumber            ItemInfo `json:"/items/ginkgo_lumber"`
	GinkgoNatureStaff       ItemInfo `json:"/items/ginkgo_nature_staff"`
	GinkgoShield            ItemInfo `json:"/items/ginkgo_shield"`
	GinkgoWaterStaff        ItemInfo `json:"/items/ginkgo_water_staff"`
	GoboBoomstick           ItemInfo `json:"/items/gobo_boomstick"`
	GoboBoots               ItemInfo `json:"/items/gobo_boots"`
	GoboBracers             ItemInfo `json:"/items/gobo_bracers"`
	GoboChaps               ItemInfo `json:"/items/gobo_chaps"`
	GoboDefender            ItemInfo `json:"/items/gobo_defender"`
	GoboEssence             ItemInfo `json:"/items/gobo_essence"`
	GoboHide                ItemInfo `json:"/items/gobo_hide"`
	GoboHood                ItemInfo `json:"/items/gobo_hood"`
	GoboLeather             ItemInfo `json:"/items/gobo_leather"`
	GoboRag                 ItemInfo `json:"/items/gobo_rag"`
	GoboShooter             ItemInfo `json:"/items/gobo_shooter"`
	GoboSlasher             ItemInfo `json:"/items/gobo_slasher"`
	GoboSmasher             ItemInfo `json:"/items/gobo_smasher"`
	GoboStabber             ItemInfo `json:"/items/gobo_stabber"`
	GoboTunic               ItemInfo `json:"/items/gobo_tunic"`
	Goggles                 ItemInfo `json:"/items/goggles"`
	GolemEssence            ItemInfo `json:"/items/golem_essence"`
	GourmetTea              ItemInfo `json:"/items/gourmet_tea"`
	GraniteBludgeon         ItemInfo `json:"/items/granite_bludgeon"`
	GreenKeyFragment        ItemInfo `json:"/items/green_key_fragment"`
	GreenTeaLeaf            ItemInfo `json:"/items/green_tea_leaf"`
	GriffinBulwark          ItemInfo `json:"/items/griffin_bulwark"`
	GriffinChaps            ItemInfo `json:"/items/griffin_chaps"`
	GriffinLeather          ItemInfo `json:"/items/griffin_leather"`
	GriffinTalon            ItemInfo `json:"/items/griffin_talon"`
	GriffinTunic            ItemInfo `json:"/items/griffin_tunic"`
	GrizzlyBearFluff        ItemInfo `json:"/items/grizzly_bear_fluff"`
	GrizzlyBearShoes        ItemInfo `json:"/items/grizzly_bear_shoes"`
	Gummy                   ItemInfo `json:"/items/gummy"`
	Heal                    ItemInfo `json:"/items/heal"`
	HolyBoots               ItemInfo `json:"/items/holy_boots"`
	HolyBrush               ItemInfo `json:"/items/holy_brush"`
	HolyBuckler             ItemInfo `json:"/items/holy_buckler"`
	HolyBulwark             ItemInfo `json:"/items/holy_bulwark"`
	HolyCheese              ItemInfo `json:"/items/holy_cheese"`
	HolyChisel              ItemInfo `json:"/items/holy_chisel"`
	HolyEnhancer            ItemInfo `json:"/items/holy_enhancer"`
	HolyGauntlets           ItemInfo `json:"/items/holy_gauntlets"`
	HolyHammer              ItemInfo `json:"/items/holy_hammer"`
	HolyHatchet             ItemInfo `json:"/items/holy_hatchet"`
	HolyHelmet              ItemInfo `json:"/items/holy_helmet"`
	HolyMace                ItemInfo `json:"/items/holy_mace"`
	HolyMilk                ItemInfo `json:"/items/holy_milk"`
	HolyNeedle              ItemInfo `json:"/items/holy_needle"`
	HolyPlateBody           ItemInfo `json:"/items/holy_plate_body"`
	HolyPlateLegs           ItemInfo `json:"/items/holy_plate_legs"`
	HolyPot                 ItemInfo `json:"/items/holy_pot"`
	HolyShears              ItemInfo `json:"/items/holy_shears"`
	HolySpatula             ItemInfo `json:"/items/holy_spatula"`
	HolySpear               ItemInfo `json:"/items/holy_spear"`
	HolySword               ItemInfo `json:"/items/holy_sword"`
	IceSpear                ItemInfo `json:"/items/ice_spear"`
	IcyCloth                ItemInfo `json:"/items/icy_cloth"`
	IcyRobeBottoms          ItemInfo `json:"/items/icy_robe_bottoms"`
	IcyRobeTop              ItemInfo `json:"/items/icy_robe_top"`
	Impale                  ItemInfo `json:"/items/impale"`
	InfernalBattlestaff     ItemInfo `json:"/items/infernal_battlestaff"`
	InfernalEmber           ItemInfo `json:"/items/infernal_ember"`
	Insanity                ItemInfo `json:"/items/insanity"`
	IntelligenceCoffee      ItemInfo `json:"/items/intelligence_coffee"`
	Invincible              ItemInfo `json:"/items/invincible"`
	JackalopeAntler         ItemInfo `json:"/items/jackalope_antler"`
	JackalopeStaff          ItemInfo `json:"/items/jackalope_staff"`
	Jade                    ItemInfo `json:"/items/jade"`
	JungleEssence           ItemInfo `json:"/items/jungle_essence"`
	KnightsAegis            ItemInfo `json:"/items/knights_aegis"`
	KnightsIngot            ItemInfo `json:"/items/knights_ingot"`
	LargeArtisansCrate      ItemInfo `json:"/items/large_artisans_crate"`
	LargeMeteoriteCache     ItemInfo `json:"/items/large_meteorite_cache"`
	LargePouch              ItemInfo `json:"/items/large_pouch"`
	LargeTreasureChest      ItemInfo `json:"/items/large_treasure_chest"`
	LibericaCoffeeBean      ItemInfo `json:"/items/liberica_coffee_bean"`
	LinenBoots              ItemInfo `json:"/items/linen_boots"`
	LinenFabric             ItemInfo `json:"/items/linen_fabric"`
	LinenGloves             ItemInfo `json:"/items/linen_gloves"`
	LinenHat                ItemInfo `json:"/items/linen_hat"`
	LinenRobeBottoms        ItemInfo `json:"/items/linen_robe_bottoms"`
	LinenRobeTop            ItemInfo `json:"/items/linen_robe_top"`
	LivingGranite           ItemInfo `json:"/items/living_granite"`
	Log                     ItemInfo `json:"/items/log"`
	LuckyCoffee             ItemInfo `json:"/items/lucky_coffee"`
	Lumber                  ItemInfo `json:"/items/lumber"`
	LunaRobeBottoms         ItemInfo `json:"/items/luna_robe_bottoms"`
	LunaRobeTop             ItemInfo `json:"/items/luna_robe_top"`
	LunaWing                ItemInfo `json:"/items/luna_wing"`
	MagicCoffee             ItemInfo `json:"/items/magic_coffee"`
	MagiciansCloth          ItemInfo `json:"/items/magicians_cloth"`
	MagiciansHat            ItemInfo `json:"/items/magicians_hat"`
	Magnet                  ItemInfo `json:"/items/magnet"`
	MagneticGloves          ItemInfo `json:"/items/magnetic_gloves"`
	MagnifyingGlass         ItemInfo `json:"/items/magnifying_glass"`
	Maim                    ItemInfo `json:"/items/maim"`
	ManaSpring              ItemInfo `json:"/items/mana_spring"`
	ManticoreShield         ItemInfo `json:"/items/manticore_shield"`
	ManticoreSting          ItemInfo `json:"/items/manticore_sting"`
	MarineChaps             ItemInfo `json:"/items/marine_chaps"`
	MarineScale             ItemInfo `json:"/items/marine_scale"`
	MarineTunic             ItemInfo `json:"/items/marine_tunic"`
	Marsberry               ItemInfo `json:"/items/marsberry"`
	MarsberryCake           ItemInfo `json:"/items/marsberry_cake"`
	MarsberryDonut          ItemInfo `json:"/items/marsberry_donut"`
	MediumArtisansCrate     ItemInfo `json:"/items/medium_artisans_crate"`
	MediumMeteoriteCache    ItemInfo `json:"/items/medium_meteorite_cache"`
	MediumPouch             ItemInfo `json:"/items/medium_pouch"`
	MediumTreasureChest     ItemInfo `json:"/items/medium_treasure_chest"`
	Milk                    ItemInfo `json:"/items/milk"`
	MilkingTea              ItemInfo `json:"/items/milking_tea"`
	MinorHeal               ItemInfo `json:"/items/minor_heal"`
	MirrorOfProtection      ItemInfo `json:"/items/mirror_of_protection"`
	Mooberry                ItemInfo `json:"/items/mooberry"`
	MooberryCake            ItemInfo `json:"/items/mooberry_cake"`
	MooberryDonut           ItemInfo `json:"/items/mooberry_donut"`
	MoolongTeaLeaf          ItemInfo `json:"/items/moolong_tea_leaf"`
	Moonstone               ItemInfo `json:"/items/moonstone"`
	NaturesVeil             ItemInfo `json:"/items/natures_veil"`
	NecklaceOfEfficiency    ItemInfo `json:"/items/necklace_of_efficiency"`
	NecklaceOfWisdom        ItemInfo `json:"/items/necklace_of_wisdom"`
	Orange                  ItemInfo `json:"/items/orange"`
	OrangeGummy             ItemInfo `json:"/items/orange_gummy"`
	OrangeKeyFragment       ItemInfo `json:"/items/orange_key_fragment"`
	OrangeYogurt            ItemInfo `json:"/items/orange_yogurt"`
	PandaFluff              ItemInfo `json:"/items/panda_fluff"`
	PandaGloves             ItemInfo `json:"/items/panda_gloves"`
	Peach                   ItemInfo `json:"/items/peach"`
	PeachGummy              ItemInfo `json:"/items/peach_gummy"`
	PeachYogurt             ItemInfo `json:"/items/peach_yogurt"`
	Pearl                   ItemInfo `json:"/items/pearl"`
	PenetratingShot         ItemInfo `json:"/items/penetrating_shot"`
	PenetratingStrike       ItemInfo `json:"/items/penetrating_strike"`
	PestilentShot           ItemInfo `json:"/items/pestilent_shot"`
	PincerGloves            ItemInfo `json:"/items/pincer_gloves"`
	Plum                    ItemInfo `json:"/items/plum"`
	PlumGummy               ItemInfo `json:"/items/plum_gummy"`
	PlumYogurt              ItemInfo `json:"/items/plum_yogurt"`
	Poke                    ItemInfo `json:"/items/poke"`
	PolarBearFluff          ItemInfo `json:"/items/polar_bear_fluff"`
	PolarBearShoes          ItemInfo `json:"/items/polar_bear_shoes"`
	PowerCoffee             ItemInfo `json:"/items/power_coffee"`
	Precision               ItemInfo `json:"/items/precision"`
	ProcessingTea           ItemInfo `json:"/items/processing_tea"`
	Provoke                 ItemInfo `json:"/items/provoke"`
	Puncture                ItemInfo `json:"/items/puncture"`
	PurpleKeyFragment       ItemInfo `json:"/items/purple_key_fragment"`
	PurpleheartBow          ItemInfo `json:"/items/purpleheart_bow"`
	PurpleheartCrossbow     ItemInfo `json:"/items/purpleheart_crossbow"`
	PurpleheartFireStaff    ItemInfo `json:"/items/purpleheart_fire_staff"`
	PurpleheartLog          ItemInfo `json:"/items/purpleheart_log"`
	PurpleheartLumber       ItemInfo `json:"/items/purpleheart_lumber"`
	PurpleheartNatureStaff  ItemInfo `json:"/items/purpleheart_nature_staff"`
	PurpleheartShield       ItemInfo `json:"/items/purpleheart_shield"`
	PurpleheartWaterStaff   ItemInfo `json:"/items/purpleheart_water_staff"`
	PurplesGift             ItemInfo `json:"/items/purples_gift"`
	QuickAid                ItemInfo `json:"/items/quick_aid"`
	QuickShot               ItemInfo `json:"/items/quick_shot"`
	RadiantBoots            ItemInfo `json:"/items/radiant_boots"`
	RadiantFabric           ItemInfo `json:"/items/radiant_fabric"`
	RadiantFiber            ItemInfo `json:"/items/radiant_fiber"`
	RadiantGloves           ItemInfo `json:"/items/radiant_gloves"`
	RadiantHat              ItemInfo `json:"/items/radiant_hat"`
	RadiantRobeBottoms      ItemInfo `json:"/items/radiant_robe_bottoms"`
	RadiantRobeTop          ItemInfo `json:"/items/radiant_robe_top"`
	RainOfArrows            ItemInfo `json:"/items/rain_of_arrows"`
	RainbowBoots            ItemInfo `json:"/items/rainbow_boots"`
	RainbowBrush            ItemInfo `json:"/items/rainbow_brush"`
	RainbowBuckler          ItemInfo `json:"/items/rainbow_buckler"`
	RainbowBulwark          ItemInfo `json:"/items/rainbow_bulwark"`
	RainbowCheese           ItemInfo `json:"/items/rainbow_cheese"`
	RainbowChisel           ItemInfo `json:"/items/rainbow_chisel"`
	RainbowEnhancer         ItemInfo `json:"/items/rainbow_enhancer"`
	RainbowGauntlets        ItemInfo `json:"/items/rainbow_gauntlets"`
	RainbowHammer           ItemInfo `json:"/items/rainbow_hammer"`
	RainbowHatchet          ItemInfo `json:"/items/rainbow_hatchet"`
	RainbowHelmet           ItemInfo `json:"/items/rainbow_helmet"`
	RainbowMace             ItemInfo `json:"/items/rainbow_mace"`
	RainbowMilk             ItemInfo `json:"/items/rainbow_milk"`
	RainbowNeedle           ItemInfo `json:"/items/rainbow_needle"`
	RainbowPlateBody        ItemInfo `json:"/items/rainbow_plate_body"`
	RainbowPlateLegs        ItemInfo `json:"/items/rainbow_plate_legs"`
	RainbowPot              ItemInfo `json:"/items/rainbow_pot"`
	RainbowShears           ItemInfo `json:"/items/rainbow_shears"`
	RainbowSpatula          ItemInfo `json:"/items/rainbow_spatula"`
	RainbowSpear            ItemInfo `json:"/items/rainbow_spear"`
	RainbowSword            ItemInfo `json:"/items/rainbow_sword"`
	RangedCoffee            ItemInfo `json:"/items/ranged_coffee"`
	RangerNecklace          ItemInfo `json:"/items/ranger_necklace"`
	RedChefsHat             ItemInfo `json:"/items/red_chefs_hat"`
	RedPandaFluff           ItemInfo `json:"/items/red_panda_fluff"`
	RedTeaLeaf              ItemInfo `json:"/items/red_tea_leaf"`
	RedwoodBow              ItemInfo `json:"/items/redwood_bow"`
	RedwoodCrossbow         ItemInfo `json:"/items/redwood_crossbow"`
	RedwoodFireStaff        ItemInfo `json:"/items/redwood_fire_staff"`
	RedwoodLog              ItemInfo `json:"/items/redwood_log"`
	RedwoodLumber           ItemInfo `json:"/items/redwood_lumber"`
	RedwoodNatureStaff      ItemInfo `json:"/items/redwood_nature_staff"`
	RedwoodShield           ItemInfo `json:"/items/redwood_shield"`
	RedwoodWaterStaff       ItemInfo `json:"/items/redwood_water_staff"`
	RegalJewel              ItemInfo `json:"/items/regal_jewel"`
	RegalSword              ItemInfo `json:"/items/regal_sword"`
	Rejuvenate              ItemInfo `json:"/items/rejuvenate"`
	ReptileBoots            ItemInfo `json:"/items/reptile_boots"`
	ReptileBracers          ItemInfo `json:"/items/reptile_bracers"`
	ReptileChaps            ItemInfo `json:"/items/reptile_chaps"`
	ReptileHide             ItemInfo `json:"/items/reptile_hide"`
	ReptileHood             ItemInfo `json:"/items/reptile_hood"`
	ReptileLeather          ItemInfo `json:"/items/reptile_leather"`
	ReptileTunic            ItemInfo `json:"/items/reptile_tunic"`
	RevenantAnima           ItemInfo `json:"/items/revenant_anima"`
	RevenantChaps           ItemInfo `json:"/items/revenant_chaps"`
	RevenantTunic           ItemInfo `json:"/items/revenant_tunic"`
	Revive                  ItemInfo `json:"/items/revive"`
	RingOfArmor             ItemInfo `json:"/items/ring_of_armor"`
	RingOfGathering         ItemInfo `json:"/items/ring_of_gathering"`
	RingOfRareFind          ItemInfo `json:"/items/ring_of_rare_find"`
	RingOfRegeneration      ItemInfo `json:"/items/ring_of_regeneration"`
	RingOfResistance        ItemInfo `json:"/items/ring_of_resistance"`
	RingOfThreat            ItemInfo `json:"/items/ring_of_threat"`
	RobustCoffeeBean        ItemInfo `json:"/items/robusta_coffee_bean"`
	RoughBoots              ItemInfo `json:"/items/rough_boots"`
	RoughBracers            ItemInfo `json:"/items/rough_bracers"`
	RoughChaps              ItemInfo `json:"/items/rough_chaps"`
	RoughHide               ItemInfo `json:"/items/rough_hide"`
	RoughHood               ItemInfo `json:"/items/rough_hood"`
	RoughLeather            ItemInfo `json:"/items/rough_leather"`
	RoughTunic              ItemInfo `json:"/items/rough_tunic"`
	RoyalCloth              ItemInfo `json:"/items/royal_cloth"`
	RoyalFireRobeBottoms    ItemInfo `json:"/items/royal_fire_robe_bottoms"`
	RoyalFireRobeTop        ItemInfo `json:"/items/royal_fire_robe_top"`
	RoyalNatureRobeBottoms  ItemInfo `json:"/items/royal_nature_robe_bottoms"`
	RoyalNatureRobeTop      ItemInfo `json:"/items/royal_nature_robe_top"`
	RoyalWaterRobeBottoms   ItemInfo `json:"/items/royal_water_robe_bottoms"`
	RoyalWaterRobeTop       ItemInfo `json:"/items/royal_water_robe_top"`
	Scratch                 ItemInfo `json:"/items/scratch"`
	ShardOfProtection       ItemInfo `json:"/items/shard_of_protection"`
	ShoebillFeather         ItemInfo `json:"/items/shoebill_feather"`
	ShoebillShoes           ItemInfo `json:"/items/shoebill_shoes"`
	SightedBracers          ItemInfo `json:"/items/sighted_bracers"`
	SilencingShot           ItemInfo `json:"/items/silencing_shot"`
	SilkBoots               ItemInfo `json:"/items/silk_boots"`
	SilkFabric              ItemInfo `json:"/items/silk_fabric"`
	SilkGloves              ItemInfo `json:"/items/silk_gloves"`
	SilkHood                ItemInfo `json:"/items/silk_hood"`
	SilkRobeBottoms         ItemInfo `json:"/items/silk_robe_bottoms"`
	SilkRobeTop             ItemInfo `json:"/items/silk_robe_top"`
	SinisterCape            ItemInfo `json:"/items/sinister_cape"`
	SinisterChest           ItemInfo `json:"/items/sinister_chest"`
	SinisterChestKey        ItemInfo `json:"/items/sinister_chest_key"`
	SinisterEntryKey        ItemInfo `json:"/items/sinister_entry_key"`
	SinisterEssence         ItemInfo `json:"/items/sinister_essence"`
	SinisterToken           ItemInfo `json:"/items/sinister_token"`
	Smack                   ItemInfo `json:"/items/smack"`
	SmallArtisansCrate      ItemInfo `json:"/items/small_artisans_crate"`
	SmallMeteoriteCache     ItemInfo `json:"/items/small_meteorite_cache"`
	SmallPouch              ItemInfo `json:"/items/small_pouch"`
	SmallTreasureChest      ItemInfo `json:"/items/small_treasure_chest"`
	SmokeBurst              ItemInfo `json:"/items/smoke_burst"`
	SnailShell              ItemInfo `json:"/items/snail_shell"`
	SnailShellHelmet        ItemInfo `json:"/items/snail_shell_helmet"`
	SnakeFang               ItemInfo `json:"/items/snake_fang"`
	SnakeFangDirk           ItemInfo `json:"/items/snake_fang_dirk"`
	SorcererBoots           ItemInfo `json:"/items/sorcerer_boots"`
	SorcererEssence         ItemInfo `json:"/items/sorcerer_essence"`
	SorcerersSole           ItemInfo `json:"/items/sorcerers_sole"`
	SoulFragment            ItemInfo `json:"/items/soul_fragment"`
	SoulHunterCrossbow      ItemInfo `json:"/items/soul_hunter_crossbow"`
	Spaceberry              ItemInfo `json:"/items/spaceberry"`
	SpaceberryCake          ItemInfo `json:"/items/spaceberry_cake"`
	SpaceberryDonut         ItemInfo `json:"/items/spaceberry_donut"`
	SpaciaCoffeeBean        ItemInfo `json:"/items/spacia_coffee_bean"`
	SpeedAura               ItemInfo `json:"/items/speed_aura"`
	SpikeShell              ItemInfo `json:"/items/spike_shell"`
	SpikedBulwark           ItemInfo `json:"/items/spiked_bulwark"`
	StalactiteShard         ItemInfo `json:"/items/stalactite_shard"`
	StalactiteSpear         ItemInfo `json:"/items/stalactite_spear"`
	StaminaCoffee           ItemInfo `json:"/items/stamina_coffee"`
	StarFragment            ItemInfo `json:"/items/star_fragment"`
	StarFruit               ItemInfo `json:"/items/star_fruit"`
	StarFruitGummy          ItemInfo `json:"/items/star_fruit_gummy"`
	StarFruitYogurt         ItemInfo `json:"/items/star_fruit_yogurt"`
	SteadyShot              ItemInfo `json:"/items/steady_shot"`
	StoneKeyFragment        ItemInfo `json:"/items/stone_key_fragment"`
	Strawberry              ItemInfo `json:"/items/strawberry"`
	StrawberryCake          ItemInfo `json:"/items/strawberry_cake"`
	StrawberryDonut         ItemInfo `json:"/items/strawberry_donut"`
	StunningBlow            ItemInfo `json:"/items/stunning_blow"`
	Sugar                   ItemInfo `json:"/items/sugar"`
	SunderingCrossbow       ItemInfo `json:"/items/sundering_crossbow"`
	SunderingJewel          ItemInfo `json:"/items/sundering_jewel"`
	SuperAttackCoffee       ItemInfo `json:"/items/super_attack_coffee"`
	SuperBrewingTea         ItemInfo `json:"/items/super_brewing_tea"`
	SuperCheesesmithingTea  ItemInfo `json:"/items/super_cheesesmithing_tea"`
	SuperCookingTea         ItemInfo `json:"/items/super_cooking_tea"`
	SuperCraftingTea        ItemInfo `json:"/items/super_crafting_tea"`
	SuperDefenseCoffee      ItemInfo `json:"/items/super_defense_coffee"`
	SuperEnhancingTea       ItemInfo `json:"/items/super_enhancing_tea"`
	SuperForagingTea        ItemInfo `json:"/items/super_foraging_tea"`
	SuperIntelligenceCoffee ItemInfo `json:"/items/super_intelligence_coffee"`
	SuperMagicCoffee        ItemInfo `json:"/items/super_magic_coffee"`
	SuperMilkingTea         ItemInfo `json:"/items/super_milking_tea"`
	SuperPowerCoffee        ItemInfo `json:"/items/super_power_coffee"`
	SuperRangedCoffee       ItemInfo `json:"/items/super_ranged_coffee"`
	SuperStaminaCoffee      ItemInfo `json:"/items/super_stamina_coffee"`
	SuperTailoringTea       ItemInfo `json:"/items/super_tailoring_tea"`
	SuperWoodcuttingTea     ItemInfo `json:"/items/super_woodcutting_tea"`
	SwampEssence            ItemInfo `json:"/items/swamp_essence"`
	Sweep                   ItemInfo `json:"/items/sweep"`
	SwiftnessCoffee         ItemInfo `json:"/items/swiftness_coffee"`
	SylvanAura              ItemInfo `json:"/items/sylvan_aura"`
	TailoringTea            ItemInfo `json:"/items/tailoring_tea"`
	TaskCrystal             ItemInfo `json:"/items/task_crystal"`
	TaskToken               ItemInfo `json:"/items/task_token"`
	Taunt                   ItemInfo `json:"/items/taunt"`
	TomeOfHealing           ItemInfo `json:"/items/tome_of_healing"`
	TomeOfTheElements       ItemInfo `json:"/items/tome_of_the_elements"`
	Toughness               ItemInfo `json:"/items/toughness"`
	ToxicPollen             ItemInfo `json:"/items/toxic_pollen"`
	TreantBark              ItemInfo `json:"/items/treant_bark"`
	TreantShield            ItemInfo `json:"/items/treant_shield"`
	TurtleShell             ItemInfo `json:"/items/turtle_shell"`
	TurtleShellBody         ItemInfo `json:"/items/turtle_shell_body"`
	TurtleShellHelmet       ItemInfo `json:"/items/turtle_shell_helmet"`
	TurtleShellLegs         ItemInfo `json:"/items/turtle_shell_legs"`
	TwilightEssence         ItemInfo `json:"/items/twilight_essence"`
	UmbralBoots             ItemInfo `json:"/items/umbral_boots"`
	UmbralBracers           ItemInfo `json:"/items/umbral_bracers"`
	UmbralChaps             ItemInfo `json:"/items/umbral_chaps"`
	UmbralHide              ItemInfo `json:"/items/umbral_hide"`
	UmbralHood              ItemInfo `json:"/items/umbral_hood"`
	UmbralLeather           ItemInfo `json:"/items/umbral_leather"`
	UmbralTunic             ItemInfo `json:"/items/umbral_tunic"`
	VampireFang             ItemInfo `json:"/items/vampire_fang"`
	VampireFangDirk         ItemInfo `json:"/items/vampire_fang_dirk"`
	VampiricBow             ItemInfo `json:"/items/vampiric_bow"`
	Vampirism               ItemInfo `json:"/items/vampirism"`
	VerdantBoots            ItemInfo `json:"/items/verdant_boots"`
	VerdantBrush            ItemInfo `json:"/items/verdant_brush"`
	VerdantBuckler          ItemInfo `json:"/items/verdant_buckler"`
	VerdantBulwark          ItemInfo `json:"/items/verdant_bulwark"`
	VerdantCheese           ItemInfo `json:"/items/verdant_cheese"`
	VerdantChisel           ItemInfo `json:"/items/verdant_chisel"`
	VerdantEnhancer         ItemInfo `json:"/items/verdant_enhancer"`
	VerdantGauntlets        ItemInfo `json:"/items/verdant_gauntlets"`
	VerdantHammer           ItemInfo `json:"/items/verdant_hammer"`
	VerdantHatchet          ItemInfo `json:"/items/verdant_hatchet"`
	VerdantHelmet           ItemInfo `json:"/items/verdant_helmet"`
	VerdantMace             ItemInfo `json:"/items/verdant_mace"`
	VerdantMilk             ItemInfo `json:"/items/verdant_milk"`
	VerdantNeedle           ItemInfo `json:"/items/verdant_needle"`
	VerdantPlateBody        ItemInfo `json:"/items/verdant_plate_body"`
	VerdantPlateLegs        ItemInfo `json:"/items/verdant_plate_legs"`
	VerdantPot              ItemInfo `json:"/items/verdant_pot"`
	VerdantShears           ItemInfo `json:"/items/verdant_shears"`
	VerdantSpatula          ItemInfo `json:"/items/verdant_spatula"`
	VerdantSpear            ItemInfo `json:"/items/verdant_spear"`
	VerdantSword            ItemInfo `json:"/items/verdant_sword"`
	VisionHelmet            ItemInfo `json:"/items/vision_helmet"`
	VisionShield            ItemInfo `json:"/items/vision_shield"`
	WatchfulRelic           ItemInfo `json:"/items/watchful_relic"`
	WaterStrike             ItemInfo `json:"/items/water_strike"`
	WerewolfClaw            ItemInfo `json:"/items/werewolf_claw"`
	WerewolfSlasher         ItemInfo `json:"/items/werewolf_slasher"`
	Wheat                   ItemInfo `json:"/items/wheat"`
	WhiteKeyFragment        ItemInfo `json:"/items/white_key_fragment"`
	WisdomCoffee            ItemInfo `json:"/items/wisdom_coffee"`
	WisdomTea               ItemInfo `json:"/items/wisdom_tea"`
	WizardNecklace          ItemInfo `json:"/items/wizard_necklace"`
	WoodcuttingTea          ItemInfo `json:"/items/woodcutting_tea"`
	WoodenBow               ItemInfo `json:"/items/wooden_bow"`
	WoodenCrossbow          ItemInfo `json:"/items/wooden_crossbow"`
	WoodenFireStaff         ItemInfo `json:"/items/wooden_fire_staff"`
	WoodenNatureStaff       ItemInfo `json:"/items/wooden_nature_staff"`
	WoodenShield            ItemInfo `json:"/items/wooden_shield"`
	WoodenWaterStaff        ItemInfo `json:"/items/wooden_water_staff"`
	Yogurt                  ItemInfo `json:"/items/yogurt"`
}

type ItemInfo struct {
	Hrid                string            `json:"hrid"`
	Name                string            `json:"name"`
	Description         string            `json:"description"`
	CategoryHrid        string            `json:"categoryHrid"`
	SellPrice           int               `json:"sellPrice"`
	IsTradable          bool              `json:"isTradable"`
	IsOpenable          bool              `json:"isOpenable"`
	OpenKeyItemHrid     string            `json:"openKeyItemHrid"`
	ItemLevel           int               `json:"itemLevel"`
	EnhancementCosts    []EnhancementCost `json:"enhancementCosts"`
	ProtectionItemHrids []string          `json:"protectionItemHrids"`
	EquipmentDetail     EquipmentDetail   `json:"equipmentDetail"`
	ConsumableDetail    ConsumableDetail  `json:"consumableDetail"`
	AbilityBookDetail   AbilityBookDetail `json:"abilityBookDetail"`
	SortIndex           int               `json:"sortIndex"`
}

type EnhancementCost struct {
	ItemHrid string `json:"itemHrid"`
	Count    int    `json:"count"`
}

type EquipmentDetail struct {
	Type                        string             `json:"type"`
	LevelRequirements           []LevelRequirement `json:"levelRequirements"`
	CombatStats                 CombatStats        `json:"combatStats"`
	NonCombatStats              NonCombatStats     `json:"nonCombatStats"`
	CombatEnhancementBonuses    CombatStats        `json:"combatEnhancementBonuses"`
	NonCombatEnhancementBonuses NonCombatStats     `json:"nonCombatEnhancementBonuses"`
}

type LevelRequirement struct {
	SkillHrid string `json:"skillHrid"`
	Level     int    `json:"level"`
}

type CombatStats struct {
	CombatStyleHrids   []string `json:"combatStyleHrids"`
	DamageType         string   `json:"damageType"`
	AttackInterval     float64  `json:"attackInterval"`
	AutoAttackDamage   float64  `json:"autoAttackDamage"`
	AttackSpeed        float64  `json:"attackSpeed"`
	CastSpeed          float64  `json:"castSpeed"`
	AbilityHaste       float64  `json:"abilityHaste"`
	CriticalRate       float64  `json:"criticalRate"`
	CriticalDamage     float64  `json:"criticalDamage"`
	StabAccuracy       float64  `json:"stabAccuracy"`
	SlashAccuracy      float64  `json:"slashAccuracy"`
	SmashAccuracy      float64  `json:"smashAccuracy"`
	RangedAccuracy     float64  `json:"rangedAccuracy"`
	MagicAccuracy      float64  `json:"magicAccuracy"`
	StabDamage         float64  `json:"stabDamage"`
	SlashDamage        float64  `json:"slashDamage"`
	SmashDamage        float64  `json:"smashDamage"`
	RangedDamage       float64  `json:"rangedDamage"`
	MagicDamage        float64  `json:"magicDamage"`
	TaskDamage         float64  `json:"taskDamage"`
	PhysicalAmplify    float64  `json:"physicalAmplify"`
	WaterAmplify       float64  `json:"waterAmplify"`
	NatureAmplify      float64  `json:"natureAmplify"`
	FireAmplify        float64  `json:"fireAmplify"`
	HealingAmplify     float64  `json:"healingAmplify"`
	ArmorPenetration   float64  `json:"armorPenetration"`
	WaterPenetration   float64  `json:"waterPenetration"`
	NaturePenetration  float64  `json:"naturePenetration"`
	FirePenetration    float64  `json:"firePenetration"`
	PhysicalThorns     float64  `json:"physicalThorns"`
	ElementalThorns    float64  `json:"elementalThorns"`
	MaxHitpoints       float64  `json:"maxHitpoints"`
	MaxManapoints      float64  `json:"maxManapoints"`
	StabEvasion        float64  `json:"stabEvasion"`
	SlashEvasion       float64  `json:"slashEvasion"`
	SmashEvasion       float64  `json:"smashEvasion"`
	RangedEvasion      float64  `json:"rangedEvasion"`
	MagicEvasion       float64  `json:"magicEvasion"`
	Armor              float64  `json:"armor"`
	WaterResistance    float64  `json:"waterResistance"`
	NatureResistance   float64  `json:"natureResistance"`
	FireResistance     float64  `json:"fireResistance"`
	DamageTaken        float64  `json:"damageTaken"`
	LifeSteal          float64  `json:"lifeSteal"`
	ManaLeech          float64  `json:"manaLeech"`
	Tenacity           float64  `json:"tenacity"`
	Threat             float64  `json:"threat"`
	HPRegen            float64  `json:"HPRegen"`
	MPRegen            float64  `json:"MPRegen"`
	CombatDropRate     float64  `json:"combatDropRate"`
	CombatDropQuantity float64  `json:"combatDropQuantity"`
	CombatRareFind     float64  `json:"combatRareFind"`
	CombatExperience   float64  `json:"combatExperience"`
	FoodSlots          int      `json:"foodSlots"`
	DrinkSlots         int      `json:"drinkSlots"`
	Weaken             float64  `json:"weaken"`
	Parry              float64  `json:"parry"`
	Mayhem             float64  `json:"mayhem"`
	Pierce             float64  `json:"pierce"`
	Curse              float64  `json:"curse"`
}

type NonCombatStats struct {
	MilkingSpeed             float64 `json:"milkingSpeed"`
	ForagingSpeed            float64 `json:"foragingSpeed"`
	WoodcuttingSpeed         float64 `json:"woodcuttingSpeed"`
	CheesesmithingSpeed      float64 `json:"cheesesmithingSpeed"`
	CraftingSpeed            float64 `json:"craftingSpeed"`
	TailoringSpeed           float64 `json:"tailoringSpeed"`
	CookingSpeed             float64 `json:"cookingSpeed"`
	BrewingSpeed             float64 `json:"brewingSpeed"`
	EnhancingSpeed           float64 `json:"enhancingSpeed"`
	TaskSpeed                float64 `json:"taskSpeed"`
	MilkingEfficiency        float64 `json:"milkingEfficiency"`
	ForagingEfficiency       float64 `json:"foragingEfficiency"`
	WoodcuttingEfficiency    float64 `json:"woodcuttingEfficiency"`
	CheesesmithingEfficiency float64 `json:"cheesesmithingEfficiency"`
	CraftingEfficiency       float64 `json:"craftingEfficiency"`
	TailoringEfficiency      float64 `json:"tailoringEfficiency"`
	CookingEfficiency        float64 `json:"cookingEfficiency"`
	BrewingEfficiency        float64 `json:"brewingEfficiency"`
	SkillingEfficiency       float64 `json:"skillingEfficiency"`
	EnhancingSuccess         float64 `json:"enhancingSuccess"`
	GatheringQuantity        float64 `json:"gatheringQuantity"`
	SkillingRareFind         float64 `json:"skillingRareFind"`
	SkillingExperience       float64 `json:"skillingExperience"`
}

type ConsumableDetail struct {
	CooldownDuration      int                     `json:"cooldownDuration"`
	UsableInActionTypeMap UsableInActionTypeMap   `json:"usableInActionTypeMap"`
	HitpointRestore       int                     `json:"hitpointRestore"`
	ManapointRestore      int                     `json:"manapointRestore"`
	RecoveryDuration      int                     `json:"recoveryDuration"`
	Buffs                 []Buff                  `json:"buffs"`
	DefaultCombatTriggers []DefaultCombatTriggers `json:"defaultCombatTriggers"`
}

type UsableInActionTypeMap struct {
	Brewing        bool `json:"/action_types/brewing"`
	Cheesesmithing bool `json:"/action_types/cheesesmithing"`
	Combat         bool `json:"/action_types/combat"`
	Cooking        bool `json:"/action_types/cooking"`
	Crafting       bool `json:"/action_types/crafting"`
	Enhancing      bool `json:"/action_types/enhancing"`
	Foraging       bool `json:"/action_types/foraging"`
	Milking        bool `json:"/action_types/milking"`
	Tailoring      bool `json:"/action_types/tailoring"`
	Woodcutting    bool `json:"/action_types/woodcutting"`
}

type Buff struct {
	UniqueHrid           string  `json:"uniqueHrid"`
	TypeHrid             string  `json:"typeHrid"`
	RatioBoost           float64 `json:"ratioBoost"`
	RatioBoostLevelBonus float64 `json:"ratioBoostLevelBonus"`
	FlatBoost            float64 `json:"flatBoost"`
	FlatBoostLevelBonus  float64 `json:"flatBoostLevelBonus"`
	StartTime            string  `json:"startTime"`
	Duration             int64   `json:"duration"`
}

type AbilityBookDetail struct {
	AbilityHrid       string             `json:"abilityHrid"`
	LevelRequirements []LevelRequirement `json:"levelRequirements"`
	ExperienceGain    int                `json:"experienceGain"`
}
